apiVersion: batch/v1
kind: Job
metadata:
  name: bakta-job
  namespace: bakta-test  
spec:
  template:
    spec:
      containers:
      - name: bakta-job
        image: quay.io/mariusdieckmann/bakta-web-job
        volumeMounts:
          - mountPath: /db
            name: database-pb
          - mountPath: /cache
            name: cache-volume
        env:
          - name: BaktaEnvConfig
            value: "--db /db /cache/demo-fasta.fasta"
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: database-pb
          persistentVolumeClaim:
            claimName: bakta-test
      restartPolicy: Never
  backoffLimit: 4